apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  storage:
    storageClass: longhorn
    size: 1Gi
  walStorage:
    size: 1Gi
    storageClass: longhorn
