apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore-full
spec:
  instances: 1

  storage:
    size: 1Gi

  bootstrap:
    recovery:
      source: pg-backup-minio
      recoveryTarget:
        targetTime: "2025-02-01 05:47:22.470494"

  externalClusters:
    - name: pg-backup-minio
      barmanObjectStore:
        destinationPath: s3://cnpgpgconf/
        endpointURL: http://minio-service:9000
        s3Credentials:
          accessKeyId:
            name: backup-storage-creds
            key: ID
          secretAccessKey:
            name: backup-storage-creds
            key: KEY
